apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-uat
  namespace: argocd         # Typically, Argo CD runs in its own namespace
spec:
  project: default          # Use an existing Argo CD project or create a new one
  source:
    repoURL: 'https://github.com/pgr-automation/GitOps_Demo_Project'
    targetRevision: main    # Or a specific branch, tag, or commit hash
    path: demo-gitops/pgr-uat         # Path to the Helm chart or configurations
    helm:
      valueFiles:           # List of value files to use for this deployment
        - values.yaml       # Base values
        - values-production.yaml # Environment-specific values
  destination:
    server: https://kubernetes.default.svc # Kubernetes API endpoint
    namespace: myapp-uat    # Namespace to deploy the app in
  syncPolicy:
    automated:
      prune: true           # Automatically remove resources no longer in Git
      selfHeal: true        # Automatically apply changes in Git
    syncOptions:
      - CreateNamespace=true # Ensure the namespace is created if it doesn't exist